// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy6fEnJvO5Gl_CbnNJKB6s1p3xAvm3D4U',
    appId: '1:785751961520:web:60890f56f2ca794b57f075',
    messagingSenderId: '785751961520',
    projectId: 'mybooks-98e7d',
    authDomain: 'mybooks-98e7d.firebaseapp.com',
    storageBucket: 'mybooks-98e7d.appspot.com',
    measurementId: 'G-6NYKJNXJB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANO7TDTn01joDAJ9cOB5O49Mg0hQ6WD1c',
    appId: '1:785751961520:android:62c866a63666e09357f075',
    messagingSenderId: '785751961520',
    projectId: 'mybooks-98e7d',
    storageBucket: 'mybooks-98e7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKC7L6Mi2ZlV5C_giXYO39xuse1f5L52c',
    appId: '1:785751961520:ios:dbd93f887862112b57f075',
    messagingSenderId: '785751961520',
    projectId: 'mybooks-98e7d',
    storageBucket: 'mybooks-98e7d.appspot.com',
    iosBundleId: 'com.example.myBooks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKC7L6Mi2ZlV5C_giXYO39xuse1f5L52c',
    appId: '1:785751961520:ios:0e87bdc66e93f24057f075',
    messagingSenderId: '785751961520',
    projectId: 'mybooks-98e7d',
    storageBucket: 'mybooks-98e7d.appspot.com',
    iosBundleId: 'com.example.myBooks.RunnerTests',
  );
}
